#-------------------------------
# Site Settings
title: Ivo Vilches
logo: # You can add own logo. For example '/images/logo.png'.
author: Ivo Vilches
description: Diseño y cosas wapas


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Now'
      url: '/now/'
    - title: 'Work'
      url: '/work/'
    # - title: 'Blog'
    #   url: '/blog/'
    - title: 'About'
      url: '/about/'


#-------------------------------
# Hero Settings
hero:
  hero__title: Hey! I'm Ivo, a freelance Product Designer, teacher, musician and hand model*
  hero__description: In this digital space you can see what I'm doing <a href="/now">right now</a>, check out <a href="/work">my work</a>, read <a href="" onclick="myFunction()">my random reflections</a> and know a little bit more <a href="/about">about me</a>.


#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Work
  portfolio__subtitle: Cool stuff people pay me to do, talks and workshops, personal projects
  portfolio__gallery:
    - image: /images/work/gfs-directory.png
      title: Community Directory
      description: A digital roster to help people connect
      client: Google for Startups
      industry: Community Management
      url: /work/gfs-directory

    - image: /images/work/no-more-haters.png
      title: No More Haters
      description: Games to fight hate speech and fake news
      client: maldita.es
      client-logo: https://miro.medium.com/max/844/1*v2mrZKEqqY80h0KpUIr-4Q.jpeg
      industry: NGO
      url: /work/no-more-haters

    - image: /images/work/poin.png
      title: POiN Places
      description: A city guide for families
      client: POiN
      industry: Family and leisure
      url: /work/poin

    - image: /images/work/arbor.png
      title: Arbor
      description: Personal finances made easy
      client: Arbor Fintech
      industry: Fintech
      url: /work/arbor

    - image: /images/work/ringo.png
      title: Ringo
      description: Agentless in-person real state tours
      client: 7r Ventures
      industry: Real State
      url: /work/ringo

    - image: /images/work/giv.png
      title: GIV.
      description: Each payment, a charitable contribution
      client: Donna Nairi
      industry: Fintech
      url: /work/giv

    - image: /images/work/trenlab.png
      title: Trenlab Trivia
      description: Games to drive engagement
      client: Wayra
      industry: 
      url: /work/trenlab

    - image: /images/work/domolock.png
      title: Domolock
      description: Technology to ease your everyday
      client: Domolock
      industry: Social Networking
      url: /work/domolock

    - image: /images/work/hocelot.png
      title: Hocelot
      description: Helping companies decide better
      client: Hocelot
      industry: Fintech
      url: /work/hocelot

    - image: /images/work/gamify.png
      title: Gamify
      description: White wooden table near brown chair
      client: Gamify
      industry: Social Networking
      url: /work/gamify

    - image: /images/work/cango.png
      title: Cango
      description: White wooden table near brown chair
      client: 7r Ventures
      industry: Real State
      url: /work/cango

    - image: /images/work/pvdesign.png
      title: pvDesign
      description: White wooden table near brown chair
      client: RatedPower
      industry: Real State
      url: /work/RatedPower


#-------------------------------
# Charlas
charlas:
  charlas__title: Talks
  charlas__subtitle: I talk about design in exchange for money and/or food
  charlas__list:
    - image: /images/work/pde.png
      title: Design for non-designers
      description: From needfinding to user testing (60 minutes)
      cta: Book now
      cta-2: More info
      url: 

    - image: /images/work/prototyping.png
      title: Prototyping 101
      description: From low fidelity wireframes to Wizard of Oz (60 minutes)
      cta: Book now
      cta-2: More info
      url: 

    - image: /images/work/material-design.png
      title: Intro to Material Design
      description: History and practice of Google's Design Language (12 hours)
      cta: Book now
      cta-2: More info
      url: 


#-------------------------------
# Projects
projects:
  project__list:

    - image: /images/sacred-video.png
      title: Old Hag's Mask
      description: I shooted and edited this video for Sacred Wolves and had a lot of fun.
      tags: video
      url: https://www.youtube.com/watch?v=zegNRk_BLoo

    - image: /images/trash-slayer.png
      title: Trash Slayer
      description: A game about slaying possessed trash bags. Coming Soon.
      tags: videogame
      url: https://twitter.com/i/events/1407614424538566656

    - image: /images/default.png
      title: Untitled-Song-01.mp3
      description: Yeah, that's the name of the song. For now. Send me your feedback!
      tags: music
      url: https://drive.google.com/file/d/1C6vHUxU4Z6d7wo0m3ODmya4e_iqeNcdc/view?usp=sharing

    - image: /images/default.png
      title: LevelUp!
      description: I produced this terrible webseries many, many years ago.
      tags: video
      url: https://www.youtube.com/watch?v=wrqt62lI--o&list=PLye0nleguaIYqa94pWLr-BUM2qz-pK5ev


#-------------------------------
# Now Settings
now:
  now__title: Now
  now__subtitle: test
  now__content:
    - image: /images/commit-sans.jpg
      title: 🧱
      description: Founding a studio called <strong>Commit Sans</strong> where we design and develop software. 0% bullshit 100% product.
      url: https://commitsans.com/
      cta: It's a Commit-ment

      # image: /images/gallery-01.jpg
    - image: /images/community-tools.png
      title: 👷‍♂️
      description: Building <strong>Community Tools</strong> to help people connect in communities in Madrid, Tel Aviv and Seoul.
      url: https://communitytools.co/
      cta: More like Commu-nice-ty Tools

    - image: /images/gallery-01.jpg
      title: 📝
      description: Teaching the Product Design course at <strong>Fictizia</strong> where we learn how to design and develop digital products.
      url: https://fictizia.com/formacion/master-ux-ui-diseno-producto-digital
      cta: An apple a day

    - image: /images/gallery-01.jpg
      title: 📚
      description: Designing an <strong>open source design knowledge base</strong> to help newcomers learn the craft and find trusted sources.
      url: https://www.notion.so/ivosdesignresources/Base-de-conocimiento-84f716996d8c4d1ba5bbf890b5d9527f
      cta: Open source that sh*t

    - image: /images/gallery-01.jpg
      title: 🎸🎤🎻
      description: Writing and recording a death metal album with symphonic elements and weird shit.
      url: https://www.instagram.com/stories/highlights/17861653984282824/
      cta: Does it djent?

    - image: /images/gallery-01.jpg
      title: 🎮
      description: Developing a game called <strong>Trash Slayer</strong>. Learning to use Unity is a real pain in the ass.
      cta: Player 1 Press Start


#-------------------------------
# Subscribe Settings
mailchimp:
  mailchimp__title: Get updates and digital art inspiration # Add your Title
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text.
  mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Footer Settings
social:
# - {icon: "ion-logo-twitter", color: "#55acee", label: Twitter, link: "https://twitter.com/ivoriginal"}
# - {icon: "ion-logo-twitter", color: "#55acee", label: Slides, link: "https://twitter.com/ivoriginal"}
# - {icon: "ion-logo-facebook", color: "#3b5999", label: Facebook, link: "https://facebook.com"}
# - {icon: "ion-logo-pinterest", color: "#bd081c", label: Pinterest, link: "https://pinterest.com"}
# - {icon: "ion-logo-dribbble", color: "#ea4c89", label: Dribbble, link: "https://dribbble.com"}
# - {icon: "ion-logo-instagram", color: "#e4405f", label: Instagram, link: "https://instagram.com"}
# - {icon: "ion ion-logo-vimeo", color: "#1393cd", label: Vimeo, link: "https://vimeo.com"}

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your email for contact form
  description: Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.