#-------------------------------
# Site Settings
title: Ivo Vilches
logo: # You can add own logo. For example '/images/logo.png'.
author: Ivo Vilches
description: Diseño y cosas wapas


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Now'
      url: '/now/'
    - title: 'Work'
      url: '/work/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'


#-------------------------------
# Hero Settings
hero:
  hero__title: Hey! I'm Ivo, a freelance Product Designer, teacher, musician and hand model*
  hero__description: In this digital space you can see what I'm doing <a href="/now">right now</a>, check out <a href="/work">my work</a>, read how I <a href="/blog">struggle to learn</a> web development and know a little bit more <a href="/about">about me</a>.


#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Work
  portfolio__subtitle: Cool stuff people pay me to do and personal projects
  portfolio__gallery:
    - image: /images/gallery-02.jpg
      title: Community Directory
      description: A digital roster to help people connect
      client: Google for Startups
      url: /portfolio/gfs-directory

    - image: /images/no-more-haters.jpg
      title: No More Haters
      description: Games to fight hate speech
      client: maldita.es
      url: no-more-haters

    - image: /images/gallery-03.jpg
      title: POiN Places
      description: A city guide for families
      client: Motherfounders
      url: poin-places

    - image: /images/gallery-03.jpg
      title: Bench Accounting
      description: White wooden table near brown chair <a href="https://unsplash.com/photos/nvzvOPQW0gc">Unsplash</a>

    - image: /images/gallery-03.jpg
      title: Bench Accounting
      description: White wooden table near brown chair <a href="https://unsplash.com/photos/nvzvOPQW0gc">Unsplash</a>

    - image: /images/gallery-03.jpg
      title: Bench Accounting
      description: White wooden table near brown chair <a href="https://unsplash.com/photos/nvzvOPQW0gc">Unsplash</a>

    - image: /images/gallery-03.jpg
      title: Bench Accounting
      description: White wooden table near brown chair <a href="https://unsplash.com/photos/nvzvOPQW0gc">Unsplash</a>


#-------------------------------
# Now Settings
now:
  now__title: Now
  now__subtitle: It's happening!
  now__content:
    - image: /images/commit-sans.jpg
      title: Founding a studio called Commit Sans
      description: where we design and develop software. 0% bullshit 100% product.
      url: commit-sans

      # image: /images/gallery-01.jpg
    - image: /images/community-tools.png
      title: Building a set of tools to help people connect
      description: in communities like Google for Startups Madrid, Tel Aviv and Seoul.
      url: community-tools

    - image: /images/gallery-01.jpg
      title: Teaching the Product Design course at Fictizia
      description: where we learn how to design and develop digital products.
      url: commit-sans

    - image: /images/gallery-01.jpg
      title: Designing an open source design knowledge base
      description: to help newcomers learn the craft and find trusted sources.
      url: commit-sans

    - image: /images/gallery-01.jpg
      title: Writing and recording a death metal album
      description: it's not actually death metal, but it really djents.

    - image: /images/gallery-01.jpg
      title: Developing a game called Trash Slayer
      description: but learning to use Unity is a real pain in the ass.


#-------------------------------
# Subscribe Settings
mailchimp:
  mailchimp__title: Get updates and digital art inspiration # Add your Title
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text.
  mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Footer Settings
social:
- {icon: "ion-logo-twitter", color: "#55acee", label: Twitter, link: "https://twitter.com"}
# - {icon: "ion-logo-facebook", color: "#3b5999", label: Facebook, link: "https://facebook.com"}
# - {icon: "ion-logo-pinterest", color: "#bd081c", label: Pinterest, link: "https://pinterest.com"}
- {icon: "ion-logo-dribbble", color: "#ea4c89", label: Dribbble, link: "https://dribbble.com"}
- {icon: "ion-logo-instagram", color: "#e4405f", label: Instagram, link: "https://instagram.com"}
# - {icon: "ion ion-logo-vimeo", color: "#1393cd", label: Vimeo, link: "https://vimeo.com"}

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your email for contact form
  description: Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.