#-------------------------------
# Site Settings
title: Ivo Vilches
logo: # You can add own logo. For example '/images/logo.png'.
author: Ivo Vilches
description: Diseño y cosas wapas


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Now'
      url: '/now/'
    - title: 'Work'
      url: '/work/'
    # - title: 'Blog'
    #   url: '/blog/'
    - title: 'About'
      url: '/about/'


#-------------------------------
# Hero Settings
hero:
  hero__title: Hey! I'm Ivo, a freelance Product Designer, teacher, musician and hand model*
  hero__description: In this digital space you can see what I'm doing <a href="/now">right now</a>, check out <a href="/work">my work</a>, read how I <a href="/blog">struggle to learn</a> web development and know a little bit more <a href="/about">about me</a>.


#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Work
  portfolio__subtitle: Cool stuff people pay me to do, talks and workshops and personal projects
  portfolio__gallery:
    - image: /images/work/gfs-directory.png
      title: Community Directory
      description: A digital roster to help people connect
      client: Google for Startups
      industry: Community Management
      url: /work/gfs-directory

    - image: /images/work/no-more-haters.png
      title: No More Haters
      description: Games to fight hate speech and fake news
      client: maldita.es
      industry: NGO
      url: no-more-haters

    - image: /images/work/poin.png
      title: POiN Places
      description: A city guide for families
      client: POiN
      industry: Family and leisure
      url: poin-places

    - image: /images/work/arbor.png
      title: Arbor
      description: White wooden table near brown chair
      client: Arbor Fintech
      industry: Fintech
      url: arbor

    - image: /images/work/ringo.png
      title: Ringo
      description: White wooden table near brown chair
      client: 7r Ventures
      industry: Real State
      url: ringo

    - image: /images/work/giv.png
      title: GIV.
      description: A city guide for families
      client: Donna Nairi
      industry: Fintech
      url: poin-places

    - image: /images/work/trenlab.png
      title: Trenlab Trivia
      description: Fun fun fun
      client: Wayra
      industry: 
      url: trenlab-trivia

    - image: /images/work/domolock.png
      title: Domolock
      description: White wooden table near brown chair
      client: Domolock
      industry: Social Networking
      url: gamify

    - image: /images/work/hocelot.png
      title: Hocelot
      description: White wooden table near brown chair
      client: Hocelot
      industry: Fintech
      url: hocelot

    - image: /images/work/gamify.png
      title: Gamify
      description: White wooden table near brown chair
      client: Gamify
      industry: Social Networking
      url: gamify

    - image: /images/work/cango.png
      title: Cango
      description: White wooden table near brown chair
      client: 7r Ventures
      industry: Real State
      url: ringo

    - image: /images/work/pvdesign.png
      title: pvDesign
      description: White wooden table near brown chair
      client: RatedPower
      industry: Real State
      url: ringo

#-------------------------------
# Charlas
charlas:
  charlas__list:
    - image: /images/work/gfs-directory.png
      title: Product Design Essentials
      description: A digital roster to help people connect
      cta: Book now
      url: /work/gfs-directory

    - image: /images/work/gfs-directory.png
      title: Prototyping
      description: A digital roster to help people connect
      cta: Book now
      url: /work/gfs-directory

    - image: /images/work/gfs-directory.png
      title: Intro to Material Design
      description: A digital roster to help people connect
      cta: Book now
      url: /work/gfs-directory


#-------------------------------
# Projects
projects:
  project__list:
    - image: 
      title: Trash Slayer
      description: A videogame
      url: /work/gfs-directory

    - image: 
      title: Fields of Oniria
      description: A digital roster to help people connect
      url: /work/gfs-directory


#-------------------------------
# Now Settings
now:
  now__title: Now
  now__subtitle: It's happening!
  now__content:
    - image: /images/commit-sans.jpg
      title: 
      description: Founding a studio called <strong>Commit Sans</strong> where we design and develop software. 0% bullshit 100% product.
      url: commit-sans
      cta: It's a Commit-ment

      # image: /images/gallery-01.jpg
    - image: /images/community-tools.png
      title: 
      description: Building <strong>Community Tools</strong> to help people connect in communities in Madrid, Tel Aviv and Seoul.
      url: community-tools
      cta: More like Commu-nice-ty Tools

    - image: /images/gallery-01.jpg
      title: 
      description: Teaching the Product Design course at <strong>Fictizia</strong> where we learn how to design and develop digital products.
      url: fictizia
      cta: An apple a day

    - image: /images/gallery-01.jpg
      title: 
      description: Designing an <strong>open source design knowledge base</strong> to help newcomers learn the craft and find trusted sources.
      url: design-resources
      cta: Open source that sh*t

    - image: /images/gallery-01.jpg
      title: 
      description: Writing and recording a death metal album with symphonic elements and weird shit.
      cta: Does it djent?

    - image: /images/gallery-01.jpg
      title: 
      description: Developing a game called <strong>Trash Slayer</strong>. Learning to use Unity is a real pain in the ass.
      cta: Player 1 Press Start


#-------------------------------
# Subscribe Settings
mailchimp:
  mailchimp__title: Get updates and digital art inspiration # Add your Title
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text.
  mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Footer Settings
social:
- {icon: "ion-logo-twitter", color: "#55acee", label: Twitter, link: "https://twitter.com"}
# - {icon: "ion-logo-facebook", color: "#3b5999", label: Facebook, link: "https://facebook.com"}
# - {icon: "ion-logo-pinterest", color: "#bd081c", label: Pinterest, link: "https://pinterest.com"}
- {icon: "ion-logo-dribbble", color: "#ea4c89", label: Dribbble, link: "https://dribbble.com"}
- {icon: "ion-logo-instagram", color: "#e4405f", label: Instagram, link: "https://instagram.com"}
# - {icon: "ion ion-logo-vimeo", color: "#1393cd", label: Vimeo, link: "https://vimeo.com"}

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your email for contact form
  description: Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.